/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.admin;

import controladores.admin.CSecciones;
import vistas.admin.alumno.PanelSeccionAlumno;

/**
 *
 * @author JALEXISRDV
 */
public class PanelSeccionesAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelVentas
     */
    public PanelSeccionesAdmin() {
        initComponents();
        this.buttonStudent.setEnabled(false);
        addEventos(new CSecciones(this));
        panelFuctionsSection.add(new PanelSeccionAlumno());
    }
    
    private void addEventos(CSecciones c) {
        buttonStudent.addActionListener(c);
        buttonTeacher.addActionListener(c);
        buttonExit.addActionListener(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSections = new javax.swing.JPanel();
        panelButtonSection = new javax.swing.JPanel();
        buttonStudent = new javax.swing.JButton();
        buttonTeacher = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        panelFuctionsSection = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 15));
        setLayout(new java.awt.BorderLayout());

        panelSections.setLayout(new java.awt.BorderLayout());

        panelButtonSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonStudent.setText("Alumno");
        buttonStudent.setFocusable(false);
        buttonStudent.setName("buttonStudent"); // NOI18N
        buttonStudent.setPreferredSize(new java.awt.Dimension(105, 50));
        panelButtonSection.add(buttonStudent);

        buttonTeacher.setText("Profesor");
        buttonTeacher.setFocusable(false);
        buttonTeacher.setName("buttonTeacher"); // NOI18N
        buttonTeacher.setPreferredSize(new java.awt.Dimension(105, 50));
        panelButtonSection.add(buttonTeacher);

        buttonExit.setText("Salir");
        buttonExit.setFocusable(false);
        buttonExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonExit.setName("buttonExit"); // NOI18N
        buttonExit.setPreferredSize(new java.awt.Dimension(105, 50));
        panelButtonSection.add(buttonExit);

        panelSections.add(panelButtonSection, java.awt.BorderLayout.NORTH);

        add(panelSections, java.awt.BorderLayout.NORTH);

        panelFuctionsSection.setLayout(new java.awt.BorderLayout());
        add(panelFuctionsSection, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JPanel getPanelFuctionsSection() {
        return panelFuctionsSection;
    }
    
    public javax.swing.JPanel getPanelButtonSection() {
        return panelButtonSection;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonStudent;
    private javax.swing.JButton buttonTeacher;
    private javax.swing.JPanel panelButtonSection;
    private javax.swing.JPanel panelFuctionsSection;
    private javax.swing.JPanel panelSections;
    // End of variables declaration//GEN-END:variables

}
