/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.admin.alumno;

import controladores.admin.alumno.CModificarAlumno;
import modelos.admin.sql.SQLAlumno;

/**
 *
 * @author JALEXISRDV
 */
public class DialogModificarAlumno extends javax.swing.JDialog {
    
    /**
     * Creates new form VentanaCamposModificarCliente
     */
    public DialogModificarAlumno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void addEventos(CModificarAlumno c) {
        buttonCancel.addActionListener(c);
        buttonSaveChanges.addActionListener(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorderLine = new javax.swing.JPanel();
        panelButtons = new javax.swing.JPanel();
        buttonSaveChanges = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        panelFields = new javax.swing.JPanel();
        panelLabels = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelLastNames = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelCellphone = new javax.swing.JLabel();
        panelCampos = new javax.swing.JPanel();
        fieldId = new javax.swing.JTextField();
        fieldName = new javax.swing.JTextField();
        fieldLastNames = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        fieldCellphone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelBorderLine.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
        panelBorderLine.setLayout(new java.awt.BorderLayout());

        panelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buttonSaveChanges.setText("Guardar Cambios");
        buttonSaveChanges.setToolTipText("");
        buttonSaveChanges.setName("buttonSaveChanges"); // NOI18N
        buttonSaveChanges.setPreferredSize(new java.awt.Dimension(141, 50));
        panelButtons.add(buttonSaveChanges);

        buttonCancel.setText("Cancelar");
        buttonCancel.setName("buttonCancel"); // NOI18N
        buttonCancel.setPreferredSize(new java.awt.Dimension(98, 50));
        panelButtons.add(buttonCancel);

        panelBorderLine.add(panelButtons, java.awt.BorderLayout.PAGE_END);

        panelFields.setLayout(new java.awt.BorderLayout(20, 0));

        panelLabels.setLayout(new java.awt.GridLayout(6, 1, 0, 15));

        labelId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelId.setText("ID Alumno:");
        panelLabels.add(labelId);

        labelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelName.setText("Nombre:");
        panelLabels.add(labelName);

        labelLastNames.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelLastNames.setText("Apellidos:");
        panelLabels.add(labelLastNames);

        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEmail.setText("Email:");
        panelLabels.add(labelEmail);

        labelCellphone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCellphone.setText("Teléfono:");
        panelLabels.add(labelCellphone);

        panelFields.add(panelLabels, java.awt.BorderLayout.WEST);

        panelCampos.setLayout(new java.awt.GridLayout(6, 1, 0, 15));

        fieldId.setColumns(20);
        panelCampos.add(fieldId);

        fieldName.setColumns(20);
        panelCampos.add(fieldName);

        fieldLastNames.setColumns(20);
        panelCampos.add(fieldLastNames);

        fieldEmail.setColumns(20);
        panelCampos.add(fieldEmail);

        fieldCellphone.setColumns(20);
        panelCampos.add(fieldCellphone);

        panelFields.add(panelCampos, java.awt.BorderLayout.CENTER);

        panelBorderLine.add(panelFields, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBorderLine, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSaveChanges;
    private javax.swing.JTextField fieldCellphone;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldLastNames;
    private javax.swing.JTextField fieldName;
    private javax.swing.JLabel labelCellphone;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelLastNames;
    private javax.swing.JLabel labelName;
    private javax.swing.JPanel panelBorderLine;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelFields;
    private javax.swing.JPanel panelLabels;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fieldCellphone
     */
    public javax.swing.JTextField getFieldCellphone() {
        return fieldCellphone;
    }

    /**
     * @return the fieldEmail
     */
    public javax.swing.JTextField getFieldEmail() {
        return fieldEmail;
    }

    /**
     * @return the fieldId
     */
    public javax.swing.JTextField getFieldId() {
        return fieldId;
    }

    /**
     * @return the fieldLastNames
     */
    public javax.swing.JTextField getFieldLastNames() {
        return fieldLastNames;
    }

    /**
     * @return the fieldName
     */
    public javax.swing.JTextField getFieldName() {
        return fieldName;
    }

}
