/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.admin.alumno;

import controladores.admin.alumno.CRegistrarAlumno;
import modelos.admin.sql.SQLAlumno;

/**
 *
 * @author JALEXISRDV
 */
public class PanelNuevoAlumno extends javax.swing.JPanel {

    /**
     * Creates new form PanelNuevoCliente
     */
    public PanelNuevoAlumno() {
        initComponents();
        addEventos(new CRegistrarAlumno(new SQLAlumno(), this));
    }
    
    private void addEventos(CRegistrarAlumno c) {
        buttonCancelRegister.addActionListener(c);
        buttonRegisterStudent.addActionListener(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfo = new javax.swing.JPanel();
        labelNewClient = new javax.swing.JLabel();
        labelInfo = new javax.swing.JLabel();
        panelFields = new javax.swing.JPanel();
        panelLabels = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelLastNames = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelCellphone = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        panelCampos = new javax.swing.JPanel();
        fieldId = new javax.swing.JTextField();
        fieldName = new javax.swing.JTextField();
        fieldLastNames = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        fieldCellphone = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        panelButtons = new javax.swing.JPanel();
        buttonRegisterStudent = new javax.swing.JButton();
        buttonCancelRegister = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        setLayout(new java.awt.BorderLayout());

        panelInfo.setLayout(new java.awt.GridLayout(2, 0));

        labelNewClient.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelNewClient.setText("NUEVO ALUMNO");
        panelInfo.add(labelNewClient);

        labelInfo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelInfo.setText("- Llene la siguiente información acerca del alumno");
        panelInfo.add(labelInfo);

        add(panelInfo, java.awt.BorderLayout.NORTH);

        panelFields.setLayout(new java.awt.BorderLayout(20, 0));

        panelLabels.setLayout(new java.awt.GridLayout(6, 1, 0, 15));

        labelId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelId.setText("ID Alumno:");
        panelLabels.add(labelId);

        labelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelName.setText("Nombre:");
        panelLabels.add(labelName);

        labelLastNames.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelLastNames.setText("Apellidos:");
        panelLabels.add(labelLastNames);

        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEmail.setText("Email:");
        panelLabels.add(labelEmail);

        labelCellphone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCellphone.setText("Teléfono:");
        panelLabels.add(labelCellphone);

        labelPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPassword.setText("Contraseña:");
        panelLabels.add(labelPassword);

        panelFields.add(panelLabels, java.awt.BorderLayout.WEST);

        panelCampos.setLayout(new java.awt.GridLayout(6, 1, 0, 15));

        fieldId.setColumns(20);
        panelCampos.add(fieldId);

        fieldName.setColumns(20);
        panelCampos.add(fieldName);

        fieldLastNames.setColumns(20);
        panelCampos.add(fieldLastNames);

        fieldEmail.setColumns(20);
        panelCampos.add(fieldEmail);

        fieldCellphone.setColumns(20);
        panelCampos.add(fieldCellphone);
        panelCampos.add(fieldPassword);

        panelFields.add(panelCampos, java.awt.BorderLayout.CENTER);

        add(panelFields, java.awt.BorderLayout.CENTER);

        panelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buttonRegisterStudent.setText("Registrar Alumno");
        buttonRegisterStudent.setName("buttonRegister"); // NOI18N
        buttonRegisterStudent.setPreferredSize(new java.awt.Dimension(141, 50));
        panelButtons.add(buttonRegisterStudent);

        buttonCancelRegister.setText("Cancelar");
        buttonCancelRegister.setName("buttonCancel"); // NOI18N
        buttonCancelRegister.setPreferredSize(new java.awt.Dimension(98, 50));
        panelButtons.add(buttonCancelRegister);

        add(panelButtons, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelRegister;
    private javax.swing.JButton buttonRegisterStudent;
    private javax.swing.JTextField fieldCellphone;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldLastNames;
    private javax.swing.JTextField fieldName;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel labelCellphone;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelLastNames;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNewClient;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelFields;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelLabels;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fieldCellphone
     */
    public javax.swing.JTextField getFieldCellphone() {
        return fieldCellphone;
    }

    /**
     * @return the fieldEmail
     */
    public javax.swing.JTextField getFieldEmail() {
        return fieldEmail;
    }

    /**
     * @return the fieldId
     */
    public javax.swing.JTextField getFieldId() {
        return fieldId;
    }

    /**
     * @return the fieldLastNames
     */
    public javax.swing.JTextField getFieldLastNames() {
        return fieldLastNames;
    }

    /**
     * @return the fieldName
     */
    public javax.swing.JTextField getFieldName() {
        return fieldName;
    }

    /**
     * @return the fieldPassword
     */
    public javax.swing.JPasswordField getFieldPassword() {
        return fieldPassword;
    }

}
