/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.admin.alumno;

import controladores.admin.alumno.CSeccionAlumno;

/**
 *
 * @author JALEXISRDV
 */
public class PanelSeccionAlumno extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    public PanelSeccionAlumno() {
        initComponents();
        this.buttonNewStudent.setEnabled(false);
        addEventos(new CSeccionAlumno(this));
        panelFieldFuction.add(new PanelNuevoAlumno());
    }
    
    private void addEventos(CSeccionAlumno c) {
        this.buttonNewStudent.addActionListener(c);
        this.buttonModifyStudent.addActionListener(c);
        this.buttonDeleteStudent.addActionListener(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFuctionsButtons = new javax.swing.JPanel();
        buttonNewStudent = new javax.swing.JButton();
        buttonModifyStudent = new javax.swing.JButton();
        buttonDeleteStudent = new javax.swing.JButton();
        panelFieldFuction = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALUMNO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 24))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        panelFuctionsButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonNewStudent.setText("Nuevo Alumno");
        buttonNewStudent.setFocusable(false);
        buttonNewStudent.setName("buttonNewStudent"); // NOI18N
        buttonNewStudent.setPreferredSize(new java.awt.Dimension(150, 50));
        panelFuctionsButtons.add(buttonNewStudent);

        buttonModifyStudent.setText("Modificar Alumno");
        buttonModifyStudent.setFocusable(false);
        buttonModifyStudent.setName("buttonModifyStudent"); // NOI18N
        buttonModifyStudent.setPreferredSize(new java.awt.Dimension(150, 50));
        panelFuctionsButtons.add(buttonModifyStudent);

        buttonDeleteStudent.setText("Eliminar Alumno");
        buttonDeleteStudent.setFocusable(false);
        buttonDeleteStudent.setName("buttonDeleteStudent"); // NOI18N
        buttonDeleteStudent.setPreferredSize(new java.awt.Dimension(150, 50));
        panelFuctionsButtons.add(buttonDeleteStudent);

        add(panelFuctionsButtons, java.awt.BorderLayout.PAGE_START);

        panelFieldFuction.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        add(panelFieldFuction, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeleteStudent;
    private javax.swing.JButton buttonModifyStudent;
    private javax.swing.JButton buttonNewStudent;
    private javax.swing.JPanel panelFieldFuction;
    private javax.swing.JPanel panelFuctionsButtons;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the panelFieldFuction
     */
    public javax.swing.JPanel getPanelFieldFuction() {
        return panelFieldFuction;
    }

    /**
     * @return the panelFuctionsButtons
     */
    public javax.swing.JPanel getPanelFuctionsButtons() {
        return panelFuctionsButtons;
    }
}
