/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.alumno;

/**
 *
 * @author JALEXISRDV
 */
public class PanelAlumno extends javax.swing.JPanel {

    /**
     * Creates new form PanelAdmin
     */
    public PanelAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMensaje = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        labelMensaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensaje.setText("CONECTADO CORRECTAMENTE COMO ALUMNO");
        add(labelMensaje, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelMensaje;
    // End of variables declaration//GEN-END:variables
}
