/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.login;

import controladores.login.CLogin;
import modelos.login.SQLValidarLogin;

/**
 *
 * @author JALEXISRDV
 */
public class PanelLogin extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogin
     */
    public PanelLogin() {
        initComponents();
        SQLValidarLogin validarLogin = new SQLValidarLogin();
        CLogin cLogin = new CLogin(this, validarLogin);
        addEventos(cLogin);
    }
    
    public void addEventos(CLogin cLogin) {
        buttonLogin.addActionListener(cLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCenter = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        panelUser = new javax.swing.JPanel();
        fieldUser = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        fieldPassword = new javax.swing.JPasswordField();
        panelButton = new javax.swing.JPanel();
        buttonLogin = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));
        setLayout(new java.awt.BorderLayout());

        panelCenter.setLayout(new java.awt.GridLayout(4, 2));

        panelLogo.setLayout(new java.awt.BorderLayout());

        labelLogo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setText("LOGO");
        panelLogo.add(labelLogo, java.awt.BorderLayout.CENTER);

        panelCenter.add(panelLogo);

        panelUser.setLayout(new java.awt.BorderLayout());

        fieldUser.setPreferredSize(new java.awt.Dimension(100, 50));
        panelUser.add(fieldUser, java.awt.BorderLayout.NORTH);

        panelCenter.add(panelUser);

        panelPassword.setLayout(new java.awt.BorderLayout());

        fieldPassword.setToolTipText("");
        fieldPassword.setPreferredSize(new java.awt.Dimension(111, 50));
        panelPassword.add(fieldPassword, java.awt.BorderLayout.NORTH);

        panelCenter.add(panelPassword);

        panelButton.setLayout(new java.awt.BorderLayout());

        buttonLogin.setText("Iniciar Sesion");
        buttonLogin.setName("btnLogin"); // NOI18N
        buttonLogin.setPreferredSize(new java.awt.Dimension(170, 50));
        panelButton.add(buttonLogin, java.awt.BorderLayout.NORTH);

        panelCenter.add(panelButton);

        add(panelCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelUser;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fieldPassword
     */
    public javax.swing.JPasswordField getFieldPassword() {
        return fieldPassword;
    }

    /**
     * @return the fieldUser
     */
    public javax.swing.JTextField getFieldUser() {
        return fieldUser;
    }
    
}
